<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::dropIfExists('iso3166');
        Schema::create('iso3166', function (Blueprint $table) {
            $table->id();
            $table->string('country');
            $table->string('flag');
            $table->timestamps();
        });
/*

SELECT
	distinct(`logs`.`itu`),
    `iso3166`.`flag`
FROM
    `logs`
LEFT JOIN
    `iso3166` ON `logs`.`itu` = `iso3166`.`country`
WHERE
    `flag` IS NULL
ORDER BY `itu`

 */
    // From https://www.qrz.com/flags on 2024-08-30
        $imports = [
            ["USA", "US"],  // My shortform

            ["Abu Ail Island", ""],
            ["Afghanistan", "AF"],
            ["Agalega and St Brandon", "MP"],
            ["Aland Islands", "AX"],
            ["Alaska", "US"],
            ["Albania", "AL"],
            ["Aldabra", ""],
            ["Algeria", "DZ"],
            ["American Samoa", "AS"],
            ["Amsterdam and St Paul Islands", "FR"],
            ["Andaman and Nicobar Islands", "IN"],
            ["Andorra", "AD"],
            ["Angola", "AO"],
            ["Anguilla", "AI"],
            ["Annobon Island", "GQ"],
            ["Antarctica", "AQ"],
            ["Antigua and Barbuda", "AG"],
            ["Argentina", "AR"],
            ["Armenia", "AM"],
            ["Aruba", "AW"],
            ["Ascension Island", "KY"],
            ["Asiatic Russia", "RU"],
            ["Auckland, Campbell Islands", "NZ"],
            ["Austral Islands", "PF"],
            ["Australia", "AU"],
            ["Austria", "AT"],
            ["Aves Island", "VE"],
            ["Azerbaijan", "AZ"],
            ["Azores", "PZ"],
            ["Bahamas", "BS"],
            ["Bahrain", "BH"],
            ["Bajo Neuvo", ""],
            ["Baker and Howland Islands", "US"],
            ["Balearic Islands", "ES"],
            ["Banaba Island", "KI"],
            ["Bangladesh", "BD"],
            ["Barbados", "BB"],
            ["Belarus", "BY"],
            ["Belgium", "BE"],
            ["Belize", "BZ"],
            ["Benin", "BJ"],
            ["Bermuda", "BM"],
            ["Bhutan", "BT"],
            ["Blenheim Reef", ""],
            ["Bolivia", "BO"],
            ["Bonaire", "BQ1"],
            ["Bosnia and Herzegovina", "BA"],
            ["Botswana", "BW"],
            ["Bouvet Island", "NO"],
            ["Brazil", "BR"],
            ["British North Borneo", ""],
            ["British Somaliland", ""],
            ["British Virgin Islands", "VG"],
            ["Brunei", "BN"],
            ["Bulgaria", "BG"],
            ["Burkina Faso", "BF"],
            ["Burundi", "BI"],
            ["Cambodia", "KH"],
            ["Cameroon", "CM"],
            ["Canada", "CA"],
            ["Canal Zone", ""],
            ["Canary Islands", "ES"],
            ["Cape Verde", "CV"],
            ["Cayman Islands", "KY"],
            ["Celebe & Molucca Is.", ""],
            ["Central African Republic", "CF"],
            ["Central Kiribati", "KI"],
            ["Ceuta and Melilla", "ES"],
            ["Chad", "TD"],
            ["Chagos Islands", "GB"],
            ["Chatham Islands", "NZ"],
            ["Chesterfield Islands", "GB"],
            ["Chile", "CL"],
            ["China", "CN"],
            ["Christmas Island", "CX"],
            ["Clipperton Island", "FR"],
            ["Cocos Island", "CR"],
            ["Cocos-Keeling Islands", "CC"],
            ["Colombia", "CO"],
            ["Comoros", "KM"],
            ["Congo", "CG"],
            ["Congo, Dem. Republic of", "CD"],
            ["Conway Reef", "FJ"],
            ["Corsica", "FR"],
            ["Costa Rica", "CR"],
            ["Crete", "GR"],
            ["Croatia", "HR"],
            ["Crozet Island", "FR"],
            ["Cuba", "CU"],
            ["Curacao", "CW"],
            ["Cyprus", "CY"],
            ["Cyprus SBA", "CY"],
            ["Czech Republic", "CZ"],
            ["Czechoslovakia", ""],
            ["Denmark", "DK"],
            ["Desecheo Island", "PR"],
            ["Desroches", ""],
            ["Djibouti", "DJ"],
            ["Dodecanese", "GR"],
            ["Dominica", "DM"],
            ["Dominican Republic", "DO"],
            ["Ducie Island", "PN"],
            ["East Kiribati", "KI"],
            ["East Malaysia", "MY"],
            ["Easter Island", "CL"],
            ["Ecuador", "EC"],
            ["Egypt", "EG"],
            ["El Salvador", "SV"],
            ["England", "GB-ENG"],
            ["Equatorial Guinea", "GQ"],
            ["Eritrea", "ER"],
            ["Estonia", "EE"],
            ["Eswatini", "SZ"],
            ["Ethiopia", "ET"],
            ["Falkland Islands", "FK"],
            ["Faroe Islands", "FO"],
            ["Farquhar", ""],
            ["Fernando de Noronha", "BR"],
            ["Fiji", "FJ"],
            ["Finland", "FI"],
            ["France", "FR"],
            ["Franz Josef Land", "RU"],
            ["French Equatorial Africa", ""],
            ["French Guiana", "FR"],
            ["French India", ""],
            ["French Indo-China", ""],
            ["French Polynesia", "PF"],
            ["French West Africa", ""],
            ["Gabon", "GA"],
            ["Galapagos Islands", "EC"],
            ["Georgia", "GE"],
            ["German Democratic Republic", ""],
            ["Germany", "DE"],
            ["Germany (OLD/East Germany)", ""],
            ["Ghana", "GH"],
            ["Gibraltar", "GI"],
            ["Glorioso Islands", "FR"],
            ["Goa", ""],
            ["Gold Coast, Togoland", ""],
            ["Greece", "GR"],
            ["Greenland", "GL"],
            ["Grenada", "GD"],
            ["Guadeloupe", "FR"],
            ["Guam", "GU"],
            ["Guantanamo Bay", "US"],
            ["Guatemala", "GT"],
            ["Guernsey", "GG"],
            ["Guinea", "GN"],
            ["Guinea-Bissau", "GW"],
            ["Guyana", "GY"],
            ["Haiti", "HT"],
            ["Hawaii", "US"],
            ["Heard Islands", "AU"],
            ["Honduras", "HN"],
            ["Hong Kong", "HK"],
            ["Hungary", "HU"],
            ["Iceland", "IS"],
            ["Ifni", ""],
            ["India", "IN"],
            ["Indonesia", "ID"],
            ["Iran", "IR"],
            ["Iraq", "IQ"],
            ["Ireland", "IE"],
            ["Isle of Man", "IM"],
            ["Israel", "IL"],
            ["Italian Somaliland", ""],
            ["Italy", "IT"],
            ["ITU Geneva", "CH"],
            ["Ivory Coast", "CI"],
            ["Jamaica", "JM"],
            ["Jan Mayen Island", "NO"],
            ["Japan", "JP"],
            ["Java", ""],
            ["Jersey", "JE"],
            ["Johnston Island", "US"],
            ["Jordan", "JO"],
            ["Juan de Nova Island", "FR"],
            ["Juan Fernandez Islands", "CL"],
            ["Kaliningrad", "RU"],
            ["Kamaran Is.", ""],
            ["Kazakhstan", "KZ"],
            ["Kenya", "KE"],
            ["Kerguelen Islands", "FR"],
            ["Kermadec Islands", "NZ"],
            ["Kingman Reef", "US"],
            ["Kiribati", "KI"],
            ["Kure Atoll", "US"],
            ["Kuwait", "KW"],
            ["Kuwait/Saudi Arabia Neutral Zone", ""],
            ["Kyrgyzstan", "KG"],
            ["Lakshadweep Islands", "IN"],
            ["Laos", "LA"],
            ["Latvia", "LV"],
            ["Lebanon", "LB"],
            ["Lesotho", "LS"],
            ["Liberia", "LR"],
            ["Libya", "LY"],
            ["Liechtenstein", "LI"],
            ["Lithuania", "LT"],
            ["Lord Howe Island", "AU"],
            ["Luxembourg", "LU"],
            ["Macau", "MO"],
            ["Macquarie Island", "AU"],
            ["Madagascar", "MG"],
            ["Madeira Island", "X2"],
            ["Malawi", "MW"],
            ["Malaya", ""],
            ["Maldives", "MV"],
            ["Mali", "ML"],
            ["Malpelo Island", "CO"],
            ["Malta", "MT"],
            ["Maly Vysotsky Island", "RU"],
            ["Manchuria", ""],
            ["Mariana Islands", "US"],
            ["Market Reef", "AX"],
            ["Marquesas Islands", "FR"],
            ["Marshall Islands", "MH"],
            ["Martinique", "MQ"],
            ["Mauritania", "MR"],
            ["Mauritius", "MU"],
            ["Mayotte", "YT"],
            ["Mellish Reef", "AU"],
            ["Mexico", "MX"],
            ["Micronesia", "FM"],
            ["Midway Islands", "US"],
            ["Minami Torishima", "JP"],
            ["Minerva Reef", ""],
            ["Moldova", "MD"],
            ["Monaco", "MC"],
            ["Mongolia", "MN"],
            ["Montenegro", "ME"],
            ["Montserrat", "MS"],
            ["Morocco", "MA"],
            ["Mozambique", "MZ"],
            ["Mt Athos", "GR"],
            ["Myanmar (Burma)", "MM"],
            ["Namibia", "NA"],
            ["Nauru", "NR"],
            ["Navassa Island", "US"],
            ["Nepal", "NP"],
            ["Netherlands", "NL"],
            ["Netherlands Antillies", "AN"],
            ["Netherlands Borneo", ""],
            ["Netherlands New Guinea", ""],
            ["New Caledonia", "NC"],
            ["New Zealand", "NZ"],
            ["Newfoundland, Labrador", ""],
            ["Nicaragua", "NI"],
            ["Niger", "NE"],
            ["Nigeria", "NG"],
            ["Niue", "NU"],
            ["Norfolk Island", "NF"],
            ["North Cook Islands", "CK"],
            ["North Korea", "KP"],
            ["North Macedonia (Republic of)", "MK"],
            ["Northern Cyprus", "ZP"],
            ["Northern Ireland", "GB-NIR"],
            ["Norway", "NO"],
            ["Ogasawara", "JP"],
            ["Okinawa (Ryukyu Is.)", ""],
            ["Okino Tori-shima", ""],
            ["Oman", "OM"],
            ["Pakistan", "PK"],
            ["Palau", "PW"],
            ["Palestine", "PS"],
            ["Palestine", ""],
            ["Palmyra, Jarvis Island", "US"],
            ["Panama", "PA"],
            ["Papua New Guinea", "PG"],
            ["Papua Territory", ""],
            ["Paraguay", "PY"],
            ["Penguin Is.", ""],
            ["People's Democratic Rep. of Yemen", ""],
            ["Peru", "PE"],
            ["Peter I Island", "NO"],
            ["Philippines", "PH"],
            ["Pitcairn Islands", "PN"],
            ["Poland", "PL"],
            ["Portugal", "PT"],
            ["Portuguese Timor", ""],
            ["Pratas Island", "TW"],
            ["Prince Edward and Marion Island", "ZA"],
            ["Puerto Rico", "PR"],
            ["Qatar", "QA"],
            ["Republic of Kosovo", "ZK"],
            ["Republic of Kosovo (NON-DXCC, Deleted)", "ZK"],
            ["Reunion", "FR"],
            ["Revillagigedo Islands", "MX"],
            ["Rodriguez Island", "MU"],
            ["Romania", "RO"],
            ["Rotuma", "FJ"],
            ["Ruanda-Urundi", ""],
            ["Russia", "RU"],
            ["Rwanda", "RW"],
            ["Saar", ""],
            ["Saba, St Eustatius", "AN"],
            ["Sable Island", "CA"],
            ["Samoa", "WS"],
            ["San Andres and Providencia", "CO"],
            ["San Felix", "CL"],
            ["San Marino", "SM"],
            ["Sao Tome & Principe", "ST"],
            ["Sardinia", "IT"],
            ["Saudi Arabia", "SA"],
            ["Saudi Arabia/Iraq Neutral Zone", "SA"],
            ["Saudi Arabia/Iraq Neutral Zone", ""],
            ["Scarborough Reef", ""],
            ["Scotland", "GB-SCT"],
            ["Senegal", "SN"],
            ["Serbia", "RS"],
            ["Serrana Bank & Roncador Cay", ""],
            ["Seychelles", "SC"],
            ["Sierra Leone", "SL"],
            ["Sikkim", ""],
            ["Singapore", "SG"],
            ["Slovak Republic", "SK"],
            ["Slovenia", "SI"],
            ["SMO Malta", "X1"],
            ["Solomon Islands", "SB"],
            ["Somalia", "SO"],
            ["South Africa", "ZA"],
            ["South Cook Islands", "GS"],
            ["South Georgia Islands", "GS"],
            ["South Korea", "KR"],
            ["South Orkney Islands", "AQ"],
            ["South Sandwich Islands", "GS"],
            ["South Shetland Islands", "GB"],
            ["South Sudan", "SS"],
            ["Southern Sudan", ""],
            ["Spain", "ES"],
            ["Spratly Islands", "PH"],
            ["Sri Lanka", "LK"],
            ["St Helena Island", "SH"],
            ["St Kitts and Nevis", "KN"],
            ["St Lucia", "LC"],
            ["St Martin", "FR"],
            ["St Paul Island", "CA"],
            ["St Peter & St Paul Rocks", "BR"],
            ["St Pierre & Miquelon", "PM"],
            ["St Vincent", "VC"],
            ["St. Barthelem", "FR"],
            ["St. Maarten", "SX"],
            ["St. Maarten, Saba, St. Eustatius", ""],
            ["Sudan", "SD"],
            ["Sumatra", ""],
            ["Suriname", "SR"],
            ["Svalbard", "NO"],
            ["Swains Island", "US"],
            ["Swan Is.", ""],
            ["Sweden", "SE"],
            ["Switzerland", "CH"],
            ["Syria", "SY"],
            ["Taiwan", "TW"],
            ["Tajikistan", "TJ"],
            ["Tangier", ""],
            ["Tanzania", "TZ"],
            ["Temotu", "SB"],
            ["Territory of New Guinea", ""],
            ["Thailand", "TH"],
            ["The Gambia", "GM"],
            ["Tibet", ""],
            ["Timor Leste", "TL"],
            ["Togo", "TG"],
            ["Tokelau Islands", "TK"],
            ["Tonga", "TO"],
            ["Trieste", ""],
            ["Trindade and Martim Vaz Island", "BR"],
            ["Trinidad and Tobago", "TT"],
            ["Tristan da Cunha and Gough Island", "GB"],
            ["Tromelin Island", "FR"],
            ["Tunisia", "TN"],
            ["Turkey", "TR"],
            ["Turkmenistan", "TM"],
            ["Turks and  Caicos Islands", "TC"],
            ["Tuvalu", "TV"],
            ["Uganda", "UG"],
            ["Ukraine", "UA"],
            ["United Arab Emirates", "AE"],
            ["United Nations", "UN"],
            ["United States", "US"],
            ["Uruguay", "UY"],
            ["US Virgin Islands", "VI"],
            ["Uzbekistan", "UZ"],
            ["Vanuatu", "VU"],
            ["Vatican", "VA"],
            ["Venezuela", "VE"],
            ["Vietnam", "VN"],
            ["Wake Island", "US"],
            ["Wales", "GB-WLS"],
            ["Wallis and Futuna Islands", "WF"],
            ["Walvis Bay", ""],
            ["West Malaysia", "MY"],
            ["Western Sahara", "EH"],
            ["Willis Island", "AU"],
            ["Yemen", "YE"],
            ["Yemen Arab Rep.", ""],
            ["Zambia", "ZM"],
            ["Zanzibar", ""],
            ["Zimbabwe", "ZW"]
        ];

        $data = [];
        foreach ($imports as $import) {
            $data[] = [
                'id' =>         null,
                'country' =>    $import[0],
                'flag' =>       strtolower($import[1]),
                'created_at' => now(),
                'updated_at' => now()
            ];
        }
        DB::table('iso3166')->insert($data);
    }


    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('iso3166');
    }
};
